all: htgzrf16

htgzrf16:
	vivado -nojournal -nolog -mode batch -source program_htgzrf16.tcl 2>&1 | tee program_htgzrf16.log

zcu111:
	vivado -nojournal -nolog -mode batch -source program_zcu111.tcl 2>&1 | tee program_zcu111.log
